### ISSUE TITLE
Free created structures

### ISSUE THREAD

**Issue by kvitajakub** [torch/tds#12]
Hello,

I am little confused about how to destruct created structures, is it necessary to call a destructor, set them to nil or something, or it doesn't matter? I assume this should be somehow addressed, as it is not managed by GC.

Could somebody point me to the explanation? Maybe it would be nice to put one or two sentences about that to the docs.

**Comment by soumith** [comment]
it is definitely handled by gc https://github.com/torch/tds/search?utf8=%E2%9C%93&q=gc
