### ISSUE TITLE
hash.pairs in the metatable.

### ISSUE THREAD

**Issue by DavidGrangier** [torch/tds#3]
hash.lua:85 defines hash.pairs in the metatable.

This means that h['pairs'] will be true, which is not convenient to check for the presence of the word pair in the hashtable.

**Comment by fmassa** [comment]
This has been fixed with https://github.com/torch/tds/commit/05ceb9c0260c5019c59efc52a5d47fe8cb137d73 , right ?

**Comment by andresy** [comment]
yes!
